import { db } from "@workspace/db";
import {
  carsTable, testimonialsTable, teamMembersTable,
  servicesTable, siteSettingsTable, blogPostsTable
} from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  // Seed settings
  const existingSettings = await db.select().from(siteSettingsTable).limit(1);
  if (!existingSettings[0]) {
    await db.insert(siteSettingsTable).values({
      dealerName: "AutoElite Motors",
      tagline: "Drive Your Dream. Experience Excellence.",
      phone: "+1 (555) 234-5678",
      whatsapp: "+15552345678",
      email: "sales@autoelitemotors.com",
      address: "4820 Automotive Boulevard",
      city: "Los Angeles, CA 90001",
      googleMapsUrl: "https://maps.google.com/?q=4820+Automotive+Boulevard+Los+Angeles+CA",
      facebookUrl: "https://facebook.com/autoelitemotors",
      instagramUrl: "https://instagram.com/autoelitemotors",
      twitterUrl: "https://twitter.com/autoelitemotors",
      youtubeUrl: "https://youtube.com/@autoelitemotors",
      openingHours: "Monday - Saturday: 9:00 AM - 7:00 PM\nSunday: 11:00 AM - 5:00 PM",
      heroTitle: "Find Your Perfect Drive",
      heroSubtitle: "Premium vehicles. Trusted service. Exceptional experience. Your dream car awaits at AutoElite Motors.",
      aboutTitle: "About AutoElite Motors",
      aboutContent: "For over 15 years, AutoElite Motors has been Los Angeles's most trusted premium car dealership. We specialize in luxury, performance, and premium vehicles, offering an unparalleled buying experience with full transparency, competitive pricing, and exceptional after-sale support. Our passionate team of automotive experts is dedicated to matching every customer with their perfect vehicle.",
      aboutImage: "https://images.unsplash.com/photo-1562141961-9e5cf8f9c0f0?w=800",
      yearsInBusiness: 15,
      carsInStock: 200,
      satisfiedClients: 5000,
    });
    console.log("Settings seeded");
  }

  // Seed cars
  const existingCars = await db.select().from(carsTable).limit(1);
  if (!existingCars[0]) {
    await db.insert(carsTable).values([
      {
        slug: "2023-mercedes-benz-gle-350",
        title: "Mercedes-Benz GLE 350",
        make: "Mercedes-Benz",
        model: "GLE",
        trim: "350",
        year: 2023,
        price: "89500",
        mileage: 12000,
        engineSize: "2.0L Turbo",
        transmission: "Automatic",
        fuelType: "Petrol",
        drivetrain: "AWD",
        bodyType: "SUV",
        seats: 5,
        doors: 4,
        color: "Obsidian Black",
        stockNumber: "AE-2023-001",
        condition: "new",
        availability: "available",
        shortDescription: "Stunning luxury SUV in pristine condition with full service history",
        description: "Experience the pinnacle of luxury SUV driving with this immaculate 2023 Mercedes-Benz GLE 350. Wrapped in Obsidian Black with a Macchiato Beige interior, this vehicle combines breathtaking style with cutting-edge technology and supreme comfort.",
        features: ["Panoramic Sunroof", "Burmester Sound System", "Heated Seats", "Wireless Charging", "360 Camera", "Active Parking Assist", "Air Suspension"],
        safetyFeatures: ["Active Brake Assist", "Blind Spot Assist", "Lane Keeping Assist", "Adaptive Cruise Control", "Traffic Sign Recognition"],
        comfortFeatures: ["MBUX Infotainment", "Apple CarPlay", "Heated & Ventilated Seats", "Dual Zone Climate", "Electric Tailgate"],
        techFeatures: ["12.3 inch Display", "MBUX Voice Control", "Wireless CarPlay", "Heads Up Display", "Digital Instrument Cluster"],
        gallery: [
          "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800",
          "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800",
          "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800",
          "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800"
        ],
        isFeatured: true,
        isPublished: true,
        financingAvailable: true,
        location: "Los Angeles, CA",
        category: "Luxury",
      },
      {
        slug: "2022-bmw-x5-m50i",
        title: "BMW X5 M50i",
        make: "BMW",
        model: "X5",
        trim: "M50i",
        year: 2022,
        price: "95000",
        mileage: 18500,
        engineSize: "4.4L V8 Twin Turbo",
        transmission: "Automatic",
        fuelType: "Petrol",
        drivetrain: "xDrive AWD",
        bodyType: "SUV",
        seats: 5,
        doors: 4,
        color: "Mineral White",
        stockNumber: "AE-2022-002",
        condition: "used",
        availability: "available",
        shortDescription: "High-performance luxury SUV with M Sport package, low mileage",
        description: "This remarkable BMW X5 M50i represents the perfect fusion of performance and luxury. With its 523hp twin-turbocharged V8 engine, this SUV delivers supercar-level performance while maintaining the versatility and comfort expected of a premium family vehicle.",
        features: ["M Sport Package", "BMW Individual", "Laser Headlights", "Panoramic Sky Lounge", "Bowers & Wilkins Sound", "Active Steering"],
        safetyFeatures: ["Automatic Emergency Braking", "Pedestrian Detection", "Rear Collision Warning", "Lane Departure Warning", "Head-Up Display"],
        comfortFeatures: ["Massage Seats", "4-Zone Climate", "Ambient Lighting", "Wireless Charging", "Executive Package"],
        techFeatures: ["BMW Live Cockpit Pro", "5G Ready", "Amazon Alexa Integration", "Gesture Control", "Wireless CarPlay"],
        gallery: [
          "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800",
          "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
          "https://images.unsplash.com/photo-1617531653332-bd46c16f4d5f?w=800"
        ],
        isFeatured: true,
        isPublished: true,
        financingAvailable: true,
        location: "Beverly Hills, CA",
        category: "Luxury",
      },
      {
        slug: "2021-porsche-cayenne-s",
        title: "Porsche Cayenne S",
        make: "Porsche",
        model: "Cayenne",
        trim: "S",
        year: 2021,
        price: "78000",
        mileage: 24000,
        engineSize: "2.9L V6 Biturbo",
        transmission: "Automatic",
        fuelType: "Petrol",
        drivetrain: "AWD",
        bodyType: "SUV",
        seats: 5,
        doors: 4,
        color: "Carrara White",
        stockNumber: "AE-2021-003",
        condition: "used",
        availability: "available",
        shortDescription: "Iconic Porsche SUV with Sport Chrono and PASM suspension",
        description: "The Porsche Cayenne S offers an unmatched combination of sports car performance and SUV versatility. This stunning Carrara White example comes loaded with the Sport Chrono Package, PASM Sport suspension, and premium Bose surround sound.",
        features: ["Sport Chrono Package", "PASM Sport Suspension", "21-inch RS Spyder Wheels", "Porsche InnoDrive", "Panoramic Roof"],
        safetyFeatures: ["Porsche Active Safety", "Lane Change Assist", "Night Vision Assist", "Surround View Camera"],
        comfortFeatures: ["14-Way Power Seats", "Heated Rear Seats", "4-Zone Climate", "Ventilated Front Seats"],
        techFeatures: ["PCM with Navigation", "Bose Surround Sound", "Apple CarPlay", "Android Auto"],
        gallery: [
          "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800",
          "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
          "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800"
        ],
        isFeatured: true,
        isPublished: true,
        financingAvailable: true,
        location: "Santa Monica, CA",
        category: "Luxury",
      },
      {
        slug: "2023-range-rover-sport-hse",
        title: "Range Rover Sport HSE",
        make: "Land Rover",
        model: "Range Rover Sport",
        trim: "HSE",
        year: 2023,
        price: "105000",
        mileage: 5500,
        engineSize: "3.0L I6 Mild Hybrid",
        transmission: "Automatic",
        fuelType: "Hybrid",
        drivetrain: "AWD",
        bodyType: "SUV",
        seats: 5,
        doors: 4,
        color: "Santorini Black",
        stockNumber: "AE-2023-004",
        condition: "new",
        availability: "available",
        shortDescription: "Nearly new Range Rover Sport with full warranty and every option",
        description: "The all-new Range Rover Sport HSE represents the ultimate blend of capability and sophistication. This nearly-new example features every available option and still carries full manufacturer warranty.",
        features: ["Dynamic Air Suspension", "Meridian Signature Sound", "Sliding Panoramic Roof", "22-inch Alloys", "Matrix LED Headlights"],
        safetyFeatures: ["Emergency Braking", "Blind Spot Monitor", "Clear Exit Monitor", "Wade Sensing", "Terrain Response 2"],
        comfortFeatures: ["SVO Ambient Lighting", "Heated Steering Wheel", "Massage Front Seats", "Cabin Air Purification"],
        techFeatures: ["Pivi Pro 11.4-inch Touchscreen", "Digital Rear View Mirror", "Activity Key", "Over-The-Air Updates"],
        gallery: [
          "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800",
          "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800",
          "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800"
        ],
        isFeatured: true,
        isPublished: true,
        financingAvailable: true,
        location: "Malibu, CA",
        category: "Luxury",
      },
      {
        slug: "2022-audi-rs6-avant",
        title: "Audi RS6 Avant",
        make: "Audi",
        model: "RS6",
        trim: "Avant",
        year: 2022,
        price: "122000",
        mileage: 9000,
        engineSize: "4.0L V8 TFSI",
        transmission: "Automatic",
        fuelType: "Petrol",
        drivetrain: "Quattro AWD",
        bodyType: "Estate",
        seats: 5,
        doors: 4,
        color: "Nardo Grey",
        stockNumber: "AE-2022-005",
        condition: "used",
        availability: "available",
        shortDescription: "The ultimate performance estate - 592hp in a practical family car",
        description: "The Audi RS6 Avant is the apex predator of the estate car world. 592hp, 0-62 in 3.6 seconds, and room for the whole family.",
        features: ["RS Dynamic Package", "Carbon Black Exterior Pack", "Bang & Olufsen 3D Sound", "Sport Exhaust", "Carbon Ceramic Brakes"],
        safetyFeatures: ["Active Lane Assist", "Side Assist", "Pre Sense Front", "360 Cameras", "Adaptive Cruise Control"],
        comfortFeatures: ["RS Sport Seats Plus", "Heated Seats", "Massage Programme", "4-Zone Climate"],
        techFeatures: ["MMI Navigation Plus", "Audi Virtual Cockpit Plus", "Head Up Display", "Wi-Fi Hotspot"],
        gallery: [
          "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
          "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800",
          "https://images.unsplash.com/photo-1617531653332-bd46c16f4d5f?w=800"
        ],
        isFeatured: true,
        isPublished: true,
        financingAvailable: true,
        location: "Los Angeles, CA",
        category: "Sports",
      },
      {
        slug: "2020-toyota-land-cruiser-200",
        title: "Toyota Land Cruiser 200",
        make: "Toyota",
        model: "Land Cruiser",
        trim: "200 Series",
        year: 2020,
        price: "68000",
        mileage: 45000,
        engineSize: "4.5L V8 Twin Turbo Diesel",
        transmission: "Automatic",
        fuelType: "Diesel",
        drivetrain: "4WD",
        bodyType: "SUV",
        seats: 7,
        doors: 4,
        color: "Pearl White",
        stockNumber: "AE-2020-006",
        condition: "used",
        availability: "available",
        shortDescription: "The legendary Land Cruiser in exceptional condition with low mileage",
        description: "The Toyota Land Cruiser 200 is the benchmark by which all other serious 4x4 vehicles are measured. Meticulous condition.",
        features: ["Kinetic Dynamic Suspension", "Crawl Control", "Multi-Terrain Select", "Centre Diff Lock", "JBL Premium Audio"],
        safetyFeatures: ["Pre-Collision System", "Lane Departure Alert", "Blind Spot Monitor", "Rear Cross Traffic Alert"],
        comfortFeatures: ["Ventilated Front Seats", "Heated Rear Seats", "3-Zone Climate Control", "Electric Sunroof"],
        techFeatures: ["Multi-Terrain Monitor", "Display Audio", "Apple CarPlay", "360 Camera System"],
        gallery: [
          "https://images.unsplash.com/photo-1626465041497-e2fd26ce18ba?w=800",
          "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800"
        ],
        isFeatured: false,
        isPublished: true,
        financingAvailable: true,
        location: "Los Angeles, CA",
        category: "SUV",
      },
      {
        slug: "2023-chevrolet-corvette-z06",
        title: "Chevrolet Corvette Z06",
        make: "Chevrolet",
        model: "Corvette",
        trim: "Z06",
        year: 2023,
        price: "110000",
        mileage: 3200,
        engineSize: "5.5L V8 Flat-Plane",
        transmission: "Automatic",
        fuelType: "Petrol",
        drivetrain: "RWD",
        bodyType: "Coupe",
        seats: 2,
        doors: 2,
        color: "Torch Red",
        stockNumber: "AE-2023-007",
        condition: "new",
        availability: "available",
        shortDescription: "American supercar with track-ready 670hp naturally aspirated V8",
        description: "The 2023 Chevrolet Corvette Z06 is Americas greatest sports car. 670hp flat-plane V8, mid-engine, and breathtaking performance.",
        features: ["Z07 Performance Package", "Carbon Fiber Aero", "Brembo Carbon Ceramic Brakes", "Magnetic Ride Control"],
        safetyFeatures: ["Automatic Emergency Braking", "Rear Camera Mirror", "Forward Collision Alert"],
        comfortFeatures: ["Heated GT2 Seats", "Head-Up Display", "8-Speaker Bose System"],
        techFeatures: ["14-inch Touchscreen", "Google Built-In", "Wireless CarPlay", "Performance Traction Management"],
        gallery: [
          "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
          "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800"
        ],
        isFeatured: true,
        isPublished: true,
        financingAvailable: true,
        location: "Los Angeles, CA",
        category: "Sports",
      },
      {
        slug: "2023-toyota-alphard-executive",
        title: "Toyota Alphard Executive Lounge",
        make: "Toyota",
        model: "Alphard",
        trim: "Executive Lounge",
        year: 2023,
        price: "72000",
        mileage: 8000,
        engineSize: "3.5L V6",
        transmission: "Automatic",
        fuelType: "Petrol",
        drivetrain: "FWD",
        bodyType: "MPV",
        seats: 7,
        doors: 4,
        color: "Platinum Pearl White",
        stockNumber: "AE-2023-010",
        condition: "new",
        availability: "available",
        shortDescription: "The ultimate luxury people carrier - Japanese royalty transport",
        description: "The Toyota Alphard Executive Lounge is the preferred vehicle of executives who demand the absolute best in premium people-moving.",
        features: ["Executive Lounge Seats", "Electric Ottoman Footrests", "Panoramic Roof", "Power Side Steps", "Privacy Curtains"],
        safetyFeatures: ["Pre-Collision System", "Lane Departure Alert", "Pedestrian Detection", "Rear Crossing Alert"],
        comfortFeatures: ["Individual Rear Captain Chairs", "Seat Heaters", "3-Zone Climate", "Rear Entertainment", "Refrigerator"],
        techFeatures: ["9-inch Rear Entertainment Screens", "Apple CarPlay", "Android Auto", "Remote Control"],
        gallery: [
          "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800",
          "https://images.unsplash.com/photo-1626465041497-e2fd26ce18ba?w=800"
        ],
        isFeatured: true,
        isPublished: true,
        financingAvailable: true,
        location: "Los Angeles, CA",
        category: "Family",
      },
      {
        slug: "2022-honda-crv-touring",
        title: "Honda CR-V Touring",
        make: "Honda",
        model: "CR-V",
        trim: "Touring",
        year: 2022,
        price: "38000",
        mileage: 22000,
        engineSize: "1.5L Turbo",
        transmission: "CVT",
        fuelType: "Petrol",
        drivetrain: "AWD",
        bodyType: "SUV",
        seats: 5,
        doors: 4,
        color: "Lunar Silver",
        stockNumber: "AE-2022-011",
        condition: "used",
        availability: "available",
        shortDescription: "Popular family SUV in top-spec Touring trim with Honda Sensing",
        description: "The Honda CR-V Touring represents exceptional value in the compact SUV segment. Fully loaded with Honda Sensing safety suite.",
        features: ["Honda Sensing Suite", "Panoramic Power Moonroof", "Leather Interior", "Wireless Charging", "Hands-Free Power Tailgate"],
        safetyFeatures: ["Collision Mitigation Braking", "Road Departure Mitigation", "Adaptive Cruise Control", "Lane Keeping Assist"],
        comfortFeatures: ["Heated Front Seats", "Power Liftgate", "Dual Zone Climate", "Cargo Tray"],
        techFeatures: ["9-inch Touchscreen", "Honda Navigation", "Apple CarPlay", "Bose Premium Sound"],
        gallery: [
          "https://images.unsplash.com/photo-1626465041497-e2fd26ce18ba?w=800",
          "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800"
        ],
        isFeatured: false,
        isPublished: true,
        financingAvailable: true,
        location: "Los Angeles, CA",
        category: "Family",
      },
      {
        slug: "2023-toyota-hilux-sr5",
        title: "Toyota Hilux SR5 Plus",
        make: "Toyota",
        model: "Hilux",
        trim: "SR5 Plus",
        year: 2023,
        price: "58000",
        mileage: 5000,
        engineSize: "2.8L Turbo Diesel",
        transmission: "Automatic",
        fuelType: "Diesel",
        drivetrain: "4WD",
        bodyType: "Pickup",
        seats: 5,
        doors: 4,
        color: "Silver Sky",
        stockNumber: "AE-2023-012",
        condition: "new",
        availability: "available",
        shortDescription: "The worlds most reliable pickup truck in premium SR5 Plus specification",
        description: "The Toyota Hilux SR5 Plus is the benchmark by which all other pickup trucks are measured. Legendary reliability meets premium luxury.",
        features: ["SR5 Plus Package", "Sports Roll Bar", "Factory Tow Bar", "Leather Seats", "18-inch Alloys", "Bull Bar"],
        safetyFeatures: ["Toyota Safety Sense", "Emergency Braking", "Lane Departure Warning", "Blind Spot Monitor"],
        comfortFeatures: ["Leather Trim Seats", "Heated Front Seats", "Dual Zone Climate", "Power Driver Seat"],
        techFeatures: ["8-inch Touchscreen", "Apple CarPlay", "Android Auto", "Satellite Navigation"],
        gallery: [
          "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800",
          "https://images.unsplash.com/photo-1626465041497-e2fd26ce18ba?w=800"
        ],
        isFeatured: false,
        isPublished: true,
        financingAvailable: true,
        location: "Los Angeles, CA",
        category: "Pickup",
      },
    ]);
    console.log("Cars seeded");
  }

  // Seed testimonials
  const existingTestimonials = await db.select().from(testimonialsTable).limit(1);
  if (!existingTestimonials[0]) {
    await db.insert(testimonialsTable).values([
      {
        name: "James Richardson",
        location: "Beverly Hills, CA",
        photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
        rating: 5,
        review: "Absolutely incredible experience. The team at AutoElite went above and beyond to find me the perfect Mercedes GLE. Professional, transparent, and genuinely passionate about cars. I will never buy from anywhere else.",
        carPurchased: "Mercedes-Benz GLE 350",
        isPublished: true,
      },
      {
        name: "Sarah Mitchell",
        location: "Malibu, CA",
        photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
        rating: 5,
        review: "From the moment I walked in, I felt like a valued customer. No pressure tactics, just genuine expertise and honest advice. My Range Rover Sport is everything I dreamed of. The financing process was smooth and fair.",
        carPurchased: "Range Rover Sport HSE",
        isPublished: true,
      },
      {
        name: "Marcus Johnson",
        location: "Santa Monica, CA",
        photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
        rating: 5,
        review: "I was skeptical about buying a used car, but AutoElite completely changed my perspective. Full vehicle history, independent inspection, and a 3-month warranty included. My BMW X5 is in flawless condition.",
        carPurchased: "BMW X5 M50i",
        isPublished: true,
      },
      {
        name: "Elena Rodriguez",
        location: "Los Angeles, CA",
        photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
        rating: 5,
        review: "The trade-in process was incredibly fair and transparent. They gave me top dollar for my old car and made the upgrade to the Porsche Cayenne seamlessly easy. Exceptional service from start to finish.",
        carPurchased: "Porsche Cayenne S",
        isPublished: true,
      },
      {
        name: "David Thompson",
        location: "Pasadena, CA",
        photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
        rating: 5,
        review: "AutoElite sourced my dream Audi RS6 Avant within 2 weeks from their network. Exactly the spec I wanted, at a fair price, with full documentation. This is how car buying should always work.",
        carPurchased: "Audi RS6 Avant",
        isPublished: true,
      },
      {
        name: "Amanda Chen",
        location: "Studio City, CA",
        photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
        rating: 5,
        review: "My husband and I both bought our cars from AutoElite within the same month. The family discount was a wonderful touch, but honestly the transparency and professionalism is why we keep coming back.",
        carPurchased: "Toyota Alphard Executive Lounge",
        isPublished: true,
      },
    ]);
    console.log("Testimonials seeded");
  }

  // Seed team members
  const existingTeam = await db.select().from(teamMembersTable).limit(1);
  if (!existingTeam[0]) {
    await db.insert(teamMembersTable).values([
      {
        name: "Michael Sterling",
        title: "Founder & Principal Dealer",
        photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400",
        specialty: "Luxury & Exotic Vehicles",
        phone: "+1 (555) 234-5678",
        whatsapp: "+15552345678",
        email: "michael@autoelitemotors.com",
        bio: "With over 20 years in the premium automotive industry, Michael founded AutoElite Motors with a vision to redefine the car buying experience in Los Angeles. His passion for extraordinary vehicles and commitment to customer satisfaction are the cornerstones of our success.",
        sortOrder: 1,
      },
      {
        name: "Alexandra Brooks",
        title: "Senior Sales Consultant",
        photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400",
        specialty: "European Luxury Brands",
        phone: "+1 (555) 234-5679",
        whatsapp: "+15552345679",
        email: "alexandra@autoelitemotors.com",
        bio: "Alexandra brings 12 years of luxury automotive experience, specializing in European marques including Mercedes-Benz, BMW, Audi, and Porsche. Her encyclopedic knowledge of these vehicles ensures every client finds their perfect match.",
        sortOrder: 2,
      },
      {
        name: "James Park",
        title: "Finance Manager",
        photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400",
        specialty: "Vehicle Financing & Leasing",
        phone: "+1 (555) 234-5680",
        whatsapp: "+15552345680",
        email: "james@autoelitemotors.com",
        bio: "James has helped thousands of clients secure the best possible financing terms for their dream vehicles. With relationships across major financial institutions, he consistently delivers competitive rates and flexible terms.",
        sortOrder: 3,
      },
      {
        name: "Sofia Martinez",
        title: "Client Relations Manager",
        photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400",
        specialty: "After-Sale Support & Trade-Ins",
        phone: "+1 (555) 234-5681",
        whatsapp: "+15552345681",
        email: "sofia@autoelitemotors.com",
        bio: "Sofia ensures that every client who leaves our showroom becomes a lifelong partner. From trade-in valuations to post-purchase support, she is dedicated to creating an exceptional experience that extends well beyond the sale.",
        sortOrder: 4,
      },
    ]);
    console.log("Team seeded");
  }

  // Seed services
  const existingServices = await db.select().from(servicesTable).limit(1);
  if (!existingServices[0]) {
    await db.insert(servicesTable).values([
      { title: "Premium Car Sales", description: "We offer an exclusive selection of verified premium vehicles from the world's leading manufacturers. Every car in our inventory undergoes a rigorous inspection process.", icon: "Car", isActive: true, sortOrder: 1 },
      { title: "Vehicle Sourcing", description: "Can't find your dream car in our current inventory? Our global network allows us to source specific makes, models, and configurations to your exact requirements.", icon: "Search", isActive: true, sortOrder: 2 },
      { title: "Financing Support", description: "We offer flexible financing options through our network of trusted financial partners. Competitive rates, straightforward terms, and quick approvals.", icon: "CreditCard", isActive: true, sortOrder: 3 },
      { title: "Trade-In Service", description: "Get a fair, transparent valuation for your current vehicle and apply it directly to your next purchase. We accept all makes and models.", icon: "ArrowLeftRight", isActive: true, sortOrder: 4 },
      { title: "Vehicle Inspection", description: "Every vehicle is subjected to a comprehensive 200-point inspection before entering our inventory. We provide full inspection reports on request.", icon: "ClipboardCheck", isActive: true, sortOrder: 5 },
      { title: "Documentation Support", description: "Our experienced team handles all paperwork including title transfers, registration, and any import documentation required.", icon: "FileText", isActive: true, sortOrder: 6 },
      { title: "After-Sale Guidance", description: "Our relationship with clients does not end at the sale. We provide ongoing support, service recommendations, and guidance for all post-purchase needs.", icon: "HeartHandshake", isActive: true, sortOrder: 7 },
      { title: "Import Assistance", description: "We specialize in sourcing and importing premium vehicles from international markets. Full customs clearance and compliance management included.", icon: "Globe", isActive: true, sortOrder: 8 },
    ]);
    console.log("Services seeded");
  }

  // Seed blog posts
  const existingBlog = await db.select().from(blogPostsTable).limit(1);
  if (!existingBlog[0]) {
    await db.insert(blogPostsTable).values([
      {
        slug: "top-luxury-suvs-2023",
        title: "Top 5 Luxury SUVs of 2023: The Ultimate Guide",
        excerpt: "The luxury SUV market has never been more competitive. We break down the top contenders and help you decide which one is right for you.",
        content: "The luxury SUV segment has evolved dramatically over the past decade. Today's premium SUVs offer performance, technology, and comfort that would have seemed impossible just a few years ago. In this comprehensive guide, we examine the five best luxury SUVs available in 2023, from the supremely capable Range Rover Sport to the technologically brilliant Mercedes GLE.\n\nWhether you prioritize performance, interior luxury, off-road capability, or cutting-edge technology, there is a perfect luxury SUV for every discerning buyer. Our expert team has driven and evaluated each of these vehicles extensively to bring you the most comprehensive and honest assessment available.",
        category: "buying-guides",
        coverImage: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800",
        isPublished: true,
        publishedAt: new Date("2023-11-01"),
      },
      {
        slug: "financing-your-dream-car",
        title: "How to Finance Your Dream Car: A Complete Guide",
        excerpt: "Understanding your financing options is key to making a smart car purchase. Our finance experts break down everything you need to know.",
        content: "Buying a premium vehicle is one of the most significant financial decisions you will make. Understanding your financing options can save you thousands of dollars and ensure you get the most favourable terms available.\n\nIn this guide, our finance team walks you through everything: from understanding interest rates and loan terms to the benefits of different financing structures. We also explain the difference between financing and leasing, and when each option might be the better choice for your situation.",
        category: "financing-tips",
        coverImage: "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800",
        isPublished: true,
        publishedAt: new Date("2023-10-15"),
      },
      {
        slug: "new-arrivals-november-2023",
        title: "November 2023 New Arrivals: Exceptional Additions to Our Inventory",
        excerpt: "This month we welcome some truly spectacular vehicles to our showroom. From a barely-used Range Rover Sport to the stunning Audi RS6 Avant.",
        content: "November has brought us some of the finest vehicles we have had the pleasure of welcoming into our inventory. Each month, we carefully select only the best examples of premium vehicles to offer our discerning clients.\n\nThis month standout addition is undoubtedly the 2022 Audi RS6 Avant in Nardo Grey with just 9,000 miles on the clock. With the full Carbon Black exterior package and Bang & Olufsen 3D sound system, this is arguably the finest RS6 Avant we have ever stocked.",
        category: "latest-arrivals",
        coverImage: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800",
        isPublished: true,
        publishedAt: new Date("2023-11-10"),
      },
    ]);
    console.log("Blog posts seeded");
  }

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
