import { Router, type IRouter } from "express";
import healthRouter from "./health";
import carsRouter from "./cars";
import inquiriesRouter from "./inquiries";
import bookingsRouter from "./bookings";
import testimonialsRouter from "./testimonials";
import blogRouter from "./blog";
import teamRouter from "./team";
import servicesRouter from "./services";
import settingsRouter from "./settings";
import adminRouter from "./admin";
import tradeInsRouter from "./trade-ins";
import financingRouter from "./financing";
import openaiRouter from "./openai/index";
import newsletterRouter from "./newsletter";
import trackRouter from "./track";
import analyticsRouter from "./analytics";
import customersRouter from "./customers";
import notificationsRouter from "./notifications";
import auditRouter from "./audit";
import adminUsersRouter from "./admin-users";
import visualSearchRouter from "./visual-search";
import voiceListingRouter from "./voice-listing";
import negotiateRouter from "./negotiate";
import recommendationsRouter from "./recommendations";
import whatsappCloudRouter from "./whatsapp-cloud";
import japanAuctionsRouter from "./japan-auctions";
import storageRouter from "./storage";
import paypalRouter from "./paypal";

const router: IRouter = Router();

router.use(healthRouter);
router.use(carsRouter);
router.use(inquiriesRouter);
router.use(bookingsRouter);
router.use(testimonialsRouter);
router.use(blogRouter);
router.use(teamRouter);
router.use(servicesRouter);
router.use(settingsRouter);
router.use(adminRouter);
router.use(tradeInsRouter);
router.use(financingRouter);
router.use(openaiRouter);
router.use(newsletterRouter);
router.use(trackRouter);
router.use(analyticsRouter);
router.use(customersRouter);
router.use(notificationsRouter);
router.use(auditRouter);
router.use(adminUsersRouter);
router.use(visualSearchRouter);
router.use(voiceListingRouter);
router.use(negotiateRouter);
router.use(recommendationsRouter);
router.use(whatsappCloudRouter);
router.use(japanAuctionsRouter);
router.use(storageRouter);
router.use(paypalRouter);

export default router;
