import { db } from "./index";
import { carsTable } from "./schema";
import { eq } from "drizzle-orm";

async function seedJapaneseCars() {
  console.log("Seeding Japanese import vehicles...");

  const japaneseCars = [
    {
      title: "2019 Toyota Land Cruiser Prado TX",
      slug: "2019-toyota-land-cruiser-prado-tx",
      make: "Toyota",
      model: "Land Cruiser Prado",
      trim: "TX",
      year: 2019,
      price: 42000,
      mileage: 48000,
      bodyType: "SUV",
      color: "Pearl White",
      fuelType: "Diesel",
      transmission: "Automatic",
      drivetrain: "4WD",
      engineSize: "2.8L Diesel",
      seats: 7,
      doors: 5,
      condition: "used",
      availability: "available",
      isFeatured: true,
      isJapaneseImport: true,
      auctionGrade: "4.5",
      chassisNumber: "GRJ150-0123456",
      shippingStatus: "arrived",
      japanDepartureDate: "2024-09-15",
      kenyaArrivalDate: "2024-10-28",
      location: "Nairobi, Kenya",
      shortDescription: "Grade 4.5 Toyota Prado TX from Japan. Low mileage, excellent condition with full service history.",
      description: "This 2019 Toyota Land Cruiser Prado TX was sourced directly from a Japanese used car auction with an outstanding grade of 4.5. Meticulously maintained with all service records from Japan available. Features leather seats, navigation, reverse camera, and parking sensors.",
      safetyFeatures: ["ABS", "Airbags (8)", "Lane Departure Warning", "Pre-Collision System", "Stability Control"],
      comfortFeatures: ["Leather Seats", "Navigation System", "Reverse Camera", "Heated Seats", "Power Sunroof", "Bluetooth", "Cruise Control"],
      gallery: [
        "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=1200",
        "https://images.unsplash.com/photo-1583267746897-2cf415887172?w=1200",
        "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200",
      ],
      viewCount: 0,
    },
    {
      title: "2020 Nissan X-Trail 20Xi",
      slug: "2020-nissan-x-trail-20xi",
      make: "Nissan",
      model: "X-Trail",
      trim: "20Xi",
      year: 2020,
      price: 28500,
      mileage: 31000,
      bodyType: "SUV",
      color: "Graphite Blue",
      fuelType: "Petrol",
      transmission: "CVT",
      drivetrain: "4WD",
      engineSize: "2.0L Petrol",
      seats: 7,
      doors: 5,
      condition: "used",
      availability: "available",
      isFeatured: false,
      isJapaneseImport: true,
      auctionGrade: "4",
      chassisNumber: "NT32-987654",
      shippingStatus: "arrived",
      japanDepartureDate: "2024-10-01",
      kenyaArrivalDate: "2024-11-10",
      location: "Nairobi, Kenya",
      shortDescription: "Grade 4 Nissan X-Trail 7-seater from Japan. Excellent family SUV with ProPilot assist.",
      description: "The 2020 Nissan X-Trail 20Xi features advanced ProPilot semi-autonomous driving. With 7 seats and 4WD capability, this is the perfect family SUV for Nairobi roads and weekend getaways.",
      safetyFeatures: ["ProPilot Assist", "ABS", "Airbags (6)", "Emergency Brake", "Blind Spot Warning"],
      comfortFeatures: ["ProPilot", "Navigation", "Around View Monitor", "Power Seats", "Dual Zone Climate", "Apple CarPlay"],
      gallery: [
        "https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=1200",
        "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200",
      ],
      viewCount: 0,
    },
    {
      title: "2021 Mazda CX-5 25S AWD",
      slug: "2021-mazda-cx5-25s-awd",
      make: "Mazda",
      model: "CX-5",
      trim: "25S AWD",
      year: 2021,
      price: 31000,
      mileage: 22000,
      bodyType: "SUV",
      color: "Soul Red Crystal",
      fuelType: "Petrol",
      transmission: "Automatic",
      drivetrain: "AWD",
      engineSize: "2.5L SKYACTIV-G",
      seats: 5,
      doors: 5,
      condition: "used",
      availability: "available",
      isFeatured: true,
      isJapaneseImport: true,
      auctionGrade: "5",
      chassisNumber: "KF2P-456789",
      shippingStatus: "arrived",
      japanDepartureDate: "2024-11-05",
      kenyaArrivalDate: "2024-12-18",
      location: "Nairobi, Kenya",
      shortDescription: "Grade 5 Mazda CX-5 in stunning Soul Red Crystal. Near-perfect condition from Japan.",
      description: "This stunning 2021 Mazda CX-5 25S received the rare Grade 5 auction score in Japan. The iconic Soul Red Crystal Metallic paint is a Mazda exclusive. Virtually showroom-quality condition with Bose audio and heads-up display.",
      safetyFeatures: ["i-Activsense", "Lane Keep Assist", "Radar Cruise Control", "AEB", "360° Safety Monitor"],
      comfortFeatures: ["Bose 12-Speaker Audio", "Heads-Up Display", "Wireless Charging", "Heated/Cooled Seats", "Sunroof", "Mazda Connect"],
      gallery: [
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200",
      ],
      viewCount: 0,
    },
    {
      title: "2018 Honda Stepwgn Spada",
      slug: "2018-honda-stepwgn-spada",
      make: "Honda",
      model: "Stepwgn",
      trim: "Spada",
      year: 2018,
      price: 24000,
      mileage: 55000,
      bodyType: "Van",
      color: "Premium White Pearl",
      fuelType: "Petrol",
      transmission: "CVT",
      drivetrain: "FWD",
      engineSize: "1.5L Turbo",
      seats: 8,
      doors: 5,
      condition: "used",
      availability: "available",
      isFeatured: false,
      isJapaneseImport: true,
      auctionGrade: "4",
      chassisNumber: "RP3-0089123",
      shippingStatus: "clearing",
      japanDepartureDate: "2025-01-10",
      kenyaArrivalDate: null,
      location: "Mombasa Port (Clearing)",
      shortDescription: "Honda Stepwgn Spada 8-seater minivan from Japan. Currently clearing at Mombasa Port.",
      description: "The Honda Stepwgn Spada is Japan's best-selling family minivan. This 8-seater features magic sliding doors and seats 3 rows comfortably. Currently clearing customs at Mombasa Port — available in approximately 2 weeks.",
      safetyFeatures: ["Honda Sensing", "AEB", "Lane Watch Camera", "Airbags (6)"],
      comfortFeatures: ["Magic Sliding Doors", "Panoramic Sunroof", "Navigation", "2nd Row Captain Seats", "Rear Entertainment"],
      gallery: [
        "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=1200",
        "https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?w=1200",
      ],
      viewCount: 0,
    },
    {
      title: "2022 Toyota Harrier Z",
      slug: "2022-toyota-harrier-z",
      make: "Toyota",
      model: "Harrier",
      trim: "Z Leather Package",
      year: 2022,
      price: 45000,
      mileage: 15000,
      bodyType: "SUV",
      color: "Emotional Red",
      fuelType: "Petrol",
      transmission: "CVT",
      drivetrain: "FWD",
      engineSize: "2.0L Dynamic Force",
      seats: 5,
      doors: 5,
      condition: "used",
      availability: "in_transit",
      isFeatured: true,
      isJapaneseImport: true,
      auctionGrade: "5",
      chassisNumber: "MXUA80-0045123",
      shippingStatus: "in_transit",
      japanDepartureDate: "2025-02-20",
      kenyaArrivalDate: "2025-04-05",
      location: "In Transit — ETA April 2025",
      shortDescription: "Grade 5 Toyota Harrier Z in rare Emotional Red. Arriving April 2025.",
      description: "The 4th generation Toyota Harrier Z sits above the RAV4 in Toyota's lineup. This Grade 5 example in Emotional Red with premium leather interior is currently in transit from Japan. Reserve now before arrival.",
      safetyFeatures: ["Toyota Safety Sense 2.0", "Pre-Collision System", "Radar Cruise Control", "Lane Tracing Assist", "Automatic High Beam"],
      comfortFeatures: ["Panoramic Glass Roof", "Digital Rear Mirror", "JBL 9-Speaker", "Wireless Apple CarPlay", "Heated/Ventilated Seats", "Digital Gauge Cluster"],
      gallery: [
        "https://images.unsplash.com/photo-1617469767786-9164a0f97d14?w=1200",
        "https://images.unsplash.com/photo-1580414057403-c5f451f30e1c?w=1200",
      ],
      viewCount: 0,
    },
  ];

  for (const car of japaneseCars) {
    const existing = await db.select().from(carsTable).where(eq(cars.slug, car.slug));
    if (existing.length === 0) {
      await db.insert(carsTable).values(car as any);
      console.log(`✓ Seeded: ${car.title}`);
    } else {
      console.log(`↺ Already exists: ${car.title}`);
    }
  }

  console.log("\n✅ Japanese import seeding complete!");
  process.exit(0);
}

seedJapaneseCars().catch(err => {
  console.error("Seed error:", err);
  process.exit(1);
});
