-- ============================================================================
-- AutoElite Motors — Seed Data
-- ============================================================================
-- This file populates a fresh database with the SAME content as the live demo:
--   • 15 cars (with images, specs, prices in KES)
--   • 3 blog posts
--   • 6 customer testimonials
--   • 8 services
--   • 4 team members
--   • Site settings (branding, contact, hours)
--   • Chatbot knowledge base
--   • Default admin user (username: admin, password: admin123)
--
-- USAGE:
--   psql "$DATABASE_URL" -f scripts/seed.sql
--
-- Or paste the entire contents into Neon/Supabase SQL editor and click Run.
--
-- This script is IDEMPOTENT — safe to re-run; it wipes & repopulates content
-- tables. It does NOT touch customer data (bookings, inquiries, etc.).
-- ============================================================================

BEGIN;

-- Clear existing content (preserves customer/transactional tables)
TRUNCATE TABLE
  cars, blog_posts, testimonials, services, team_members,
  site_settings, chatbot_knowledge, admin_users
RESTART IDENTITY CASCADE;

-- ============================================================================
-- Content data (dumped from live database)
-- ============================================================================


-- Data for Name: blog_posts; Type: TABLE DATA; Schema: public; Owner: -

INSERT INTO public.blog_posts VALUES (1, 'top-luxury-suvs-2023', 'Top 5 Luxury SUVs of 2023: The Ultimate Guide', 'The luxury SUV market has never been more competitive. We break down the top contenders and help you decide which one is right for you.', 'The luxury SUV segment has evolved dramatically over the past decade. Today''s premium SUVs offer performance, technology, and comfort that would have seemed impossible just a few years ago. In this comprehensive guide, we examine the five best luxury SUVs available in 2023, from the supremely capable Range Rover Sport to the technologically brilliant Mercedes GLE.

Whether you prioritize performance, interior luxury, off-road capability, or cutting-edge technology, there is a perfect luxury SUV for every discerning buyer. Our expert team has driven and evaluated each of these vehicles extensively to bring you the most comprehensive and honest assessment available.', 'buying-guides', 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800', true, '2023-11-01 00:00:00', '2026-04-12 11:09:50.931834');
INSERT INTO public.blog_posts VALUES (2, 'financing-your-dream-car', 'How to Finance Your Dream Car: A Complete Guide', 'Understanding your financing options is key to making a smart car purchase. Our finance experts break down everything you need to know.', 'Buying a premium vehicle is one of the most significant financial decisions you will make. Understanding your financing options can save you thousands of dollars and ensure you get the most favourable terms available.

In this guide, our finance team walks you through everything: from understanding interest rates and loan terms to the benefits of different financing structures. We also explain the difference between financing and leasing, and when each option might be the better choice for your situation.', 'financing-tips', 'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800', true, '2023-10-15 00:00:00', '2026-04-12 11:09:50.931834');
INSERT INTO public.blog_posts VALUES (3, 'new-arrivals-november-2023', 'November 2023 New Arrivals: Exceptional Additions to Our Inventory', 'This month we welcome some truly spectacular vehicles to our showroom. From a barely-used Range Rover Sport to the stunning Audi RS6 Avant.', 'November has brought us some of the finest vehicles we have had the pleasure of welcoming into our inventory. Each month, we carefully select only the best examples of premium vehicles to offer our discerning clients.

This month standout addition is undoubtedly the 2022 Audi RS6 Avant in Nardo Grey with just 9,000 miles on the clock. With the full Carbon Black exterior package and Bang & Olufsen 3D sound system, this is arguably the finest RS6 Avant we have ever stocked.', 'latest-arrivals', 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800', true, '2023-11-10 00:00:00', '2026-04-12 11:09:50.931834');


-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: -

INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (1, '2023-mercedes-benz-gle-350', 'Mercedes-Benz GLE 350', 'Mercedes-Benz', 'GLE', '350', 2023, 89500.00, NULL, 12000, '2.0L Turbo', 'Automatic', 'Petrol', 'AWD', 'SUV', 5, 4, 'Obsidian Black', 'AE-2023-001', NULL, 'new', 'available', 'Stunning luxury SUV in pristine condition with full service history', 'Experience the pinnacle of luxury SUV driving with this immaculate 2023 Mercedes-Benz GLE 350. Wrapped in Obsidian Black with a Macchiato Beige interior, this vehicle combines breathtaking style with cutting-edge technology and supreme comfort.', '["Panoramic Sunroof", "Burmester Sound System", "Heated Seats", "Wireless Charging", "360 Camera", "Active Parking Assist", "Air Suspension"]', '["Active Brake Assist", "Blind Spot Assist", "Lane Keeping Assist", "Adaptive Cruise Control", "Traffic Sign Recognition"]', '["MBUX Infotainment", "Apple CarPlay", "Heated & Ventilated Seats", "Dual Zone Climate", "Electric Tailgate"]', '["12.3 inch Display", "MBUX Voice Control", "Wireless CarPlay", "Heads Up Display", "Digital Instrument Cluster"]', '["https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800", "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800", "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800", "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800"]', NULL, true, true, true, 'Los Angeles, CA', 'Luxury', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (2, '2022-bmw-x5-m50i', 'BMW X5 M50i', 'BMW', 'X5', 'M50i', 2022, 95000.00, NULL, 18500, '4.4L V8 Twin Turbo', 'Automatic', 'Petrol', 'xDrive AWD', 'SUV', 5, 4, 'Mineral White', 'AE-2022-002', NULL, 'used', 'available', 'High-performance luxury SUV with M Sport package, low mileage', 'This remarkable BMW X5 M50i represents the perfect fusion of performance and luxury. With its 523hp twin-turbocharged V8 engine, this SUV delivers supercar-level performance while maintaining the versatility and comfort expected of a premium family vehicle.', '["M Sport Package", "BMW Individual", "Laser Headlights", "Panoramic Sky Lounge", "Bowers & Wilkins Sound", "Active Steering"]', '["Automatic Emergency Braking", "Pedestrian Detection", "Rear Collision Warning", "Lane Departure Warning", "Head-Up Display"]', '["Massage Seats", "4-Zone Climate", "Ambient Lighting", "Wireless Charging", "Executive Package"]', '["BMW Live Cockpit Pro", "5G Ready", "Amazon Alexa Integration", "Gesture Control", "Wireless CarPlay"]', '["https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800", "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800", "https://images.unsplash.com/photo-1617531653332-bd46c16f4d5f?w=800"]', NULL, true, true, true, 'Beverly Hills, CA', 'Luxury', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (3, '2021-porsche-cayenne-s', 'Porsche Cayenne S', 'Porsche', 'Cayenne', 'S', 2021, 78000.00, NULL, 24000, '2.9L V6 Biturbo', 'Automatic', 'Petrol', 'AWD', 'SUV', 5, 4, 'Carrara White', 'AE-2021-003', NULL, 'used', 'available', 'Iconic Porsche SUV with Sport Chrono and PASM suspension', 'The Porsche Cayenne S offers an unmatched combination of sports car performance and SUV versatility. This stunning Carrara White example comes loaded with the Sport Chrono Package, PASM Sport suspension, and premium Bose surround sound.', '["Sport Chrono Package", "PASM Sport Suspension", "21-inch RS Spyder Wheels", "Porsche InnoDrive", "Panoramic Roof"]', '["Porsche Active Safety", "Lane Change Assist", "Night Vision Assist", "Surround View Camera"]', '["14-Way Power Seats", "Heated Rear Seats", "4-Zone Climate", "Ventilated Front Seats"]', '["PCM with Navigation", "Bose Surround Sound", "Apple CarPlay", "Android Auto"]', '["https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800", "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800", "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800"]', NULL, true, true, true, 'Santa Monica, CA', 'Luxury', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (4, '2023-range-rover-sport-hse', 'Range Rover Sport HSE', 'Land Rover', 'Range Rover Sport', 'HSE', 2023, 105000.00, NULL, 5500, '3.0L I6 Mild Hybrid', 'Automatic', 'Hybrid', 'AWD', 'SUV', 5, 4, 'Santorini Black', 'AE-2023-004', NULL, 'new', 'available', 'Nearly new Range Rover Sport with full warranty and every option', 'The all-new Range Rover Sport HSE represents the ultimate blend of capability and sophistication. This nearly-new example features every available option and still carries full manufacturer warranty.', '["Dynamic Air Suspension", "Meridian Signature Sound", "Sliding Panoramic Roof", "22-inch Alloys", "Matrix LED Headlights"]', '["Emergency Braking", "Blind Spot Monitor", "Clear Exit Monitor", "Wade Sensing", "Terrain Response 2"]', '["SVO Ambient Lighting", "Heated Steering Wheel", "Massage Front Seats", "Cabin Air Purification"]', '["Pivi Pro 11.4-inch Touchscreen", "Digital Rear View Mirror", "Activity Key", "Over-The-Air Updates"]', '["https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800", "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800", "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800"]', NULL, true, true, true, 'Malibu, CA', 'Luxury', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (5, '2022-audi-rs6-avant', 'Audi RS6 Avant', 'Audi', 'RS6', 'Avant', 2022, 122000.00, NULL, 9000, '4.0L V8 TFSI', 'Automatic', 'Petrol', 'Quattro AWD', 'Estate', 5, 4, 'Nardo Grey', 'AE-2022-005', NULL, 'used', 'available', 'The ultimate performance estate - 592hp in a practical family car', 'The Audi RS6 Avant is the apex predator of the estate car world. 592hp, 0-62 in 3.6 seconds, and room for the whole family.', '["RS Dynamic Package", "Carbon Black Exterior Pack", "Bang & Olufsen 3D Sound", "Sport Exhaust", "Carbon Ceramic Brakes"]', '["Active Lane Assist", "Side Assist", "Pre Sense Front", "360 Cameras", "Adaptive Cruise Control"]', '["RS Sport Seats Plus", "Heated Seats", "Massage Programme", "4-Zone Climate"]', '["MMI Navigation Plus", "Audi Virtual Cockpit Plus", "Head Up Display", "Wi-Fi Hotspot"]', '["https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800", "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800", "https://images.unsplash.com/photo-1617531653332-bd46c16f4d5f?w=800"]', NULL, true, true, true, 'Los Angeles, CA', 'Sports', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (6, '2020-toyota-land-cruiser-200', 'Toyota Land Cruiser 200', 'Toyota', 'Land Cruiser', '200 Series', 2020, 68000.00, NULL, 45000, '4.5L V8 Twin Turbo Diesel', 'Automatic', 'Diesel', '4WD', 'SUV', 7, 4, 'Pearl White', 'AE-2020-006', NULL, 'used', 'available', 'The legendary Land Cruiser in exceptional condition with low mileage', 'The Toyota Land Cruiser 200 is the benchmark by which all other serious 4x4 vehicles are measured. Meticulous condition.', '["Kinetic Dynamic Suspension", "Crawl Control", "Multi-Terrain Select", "Centre Diff Lock", "JBL Premium Audio"]', '["Pre-Collision System", "Lane Departure Alert", "Blind Spot Monitor", "Rear Cross Traffic Alert"]', '["Ventilated Front Seats", "Heated Rear Seats", "3-Zone Climate Control", "Electric Sunroof"]', '["Multi-Terrain Monitor", "Display Audio", "Apple CarPlay", "360 Camera System"]', '["https://images.unsplash.com/photo-1626465041497-e2fd26ce18ba?w=800", "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800"]', NULL, false, true, true, 'Los Angeles, CA', 'SUV', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (7, '2023-chevrolet-corvette-z06', 'Chevrolet Corvette Z06', 'Chevrolet', 'Corvette', 'Z06', 2023, 110000.00, NULL, 3200, '5.5L V8 Flat-Plane', 'Automatic', 'Petrol', 'RWD', 'Coupe', 2, 2, 'Torch Red', 'AE-2023-007', NULL, 'new', 'available', 'American supercar with track-ready 670hp naturally aspirated V8', 'The 2023 Chevrolet Corvette Z06 is Americas greatest sports car. 670hp flat-plane V8, mid-engine, and breathtaking performance.', '["Z07 Performance Package", "Carbon Fiber Aero", "Brembo Carbon Ceramic Brakes", "Magnetic Ride Control"]', '["Automatic Emergency Braking", "Rear Camera Mirror", "Forward Collision Alert"]', '["Heated GT2 Seats", "Head-Up Display", "8-Speaker Bose System"]', '["14-inch Touchscreen", "Google Built-In", "Wireless CarPlay", "Performance Traction Management"]', '["https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800", "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800"]', NULL, true, true, true, 'Los Angeles, CA', 'Sports', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (8, '2023-toyota-alphard-executive', 'Toyota Alphard Executive Lounge', 'Toyota', 'Alphard', 'Executive Lounge', 2023, 72000.00, NULL, 8000, '3.5L V6', 'Automatic', 'Petrol', 'FWD', 'MPV', 7, 4, 'Platinum Pearl White', 'AE-2023-010', NULL, 'new', 'available', 'The ultimate luxury people carrier - Japanese royalty transport', 'The Toyota Alphard Executive Lounge is the preferred vehicle of executives who demand the absolute best in premium people-moving.', '["Executive Lounge Seats", "Electric Ottoman Footrests", "Panoramic Roof", "Power Side Steps", "Privacy Curtains"]', '["Pre-Collision System", "Lane Departure Alert", "Pedestrian Detection", "Rear Crossing Alert"]', '["Individual Rear Captain Chairs", "Seat Heaters", "3-Zone Climate", "Rear Entertainment", "Refrigerator"]', '["9-inch Rear Entertainment Screens", "Apple CarPlay", "Android Auto", "Remote Control"]', '["https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=800", "https://images.unsplash.com/photo-1626465041497-e2fd26ce18ba?w=800"]', NULL, true, true, true, 'Los Angeles, CA', 'Family', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (9, '2022-honda-crv-touring', 'Honda CR-V Touring', 'Honda', 'CR-V', 'Touring', 2022, 38000.00, NULL, 22000, '1.5L Turbo', 'CVT', 'Petrol', 'AWD', 'SUV', 5, 4, 'Lunar Silver', 'AE-2022-011', NULL, 'used', 'available', 'Popular family SUV in top-spec Touring trim with Honda Sensing', 'The Honda CR-V Touring represents exceptional value in the compact SUV segment. Fully loaded with Honda Sensing safety suite.', '["Honda Sensing Suite", "Panoramic Power Moonroof", "Leather Interior", "Wireless Charging", "Hands-Free Power Tailgate"]', '["Collision Mitigation Braking", "Road Departure Mitigation", "Adaptive Cruise Control", "Lane Keeping Assist"]', '["Heated Front Seats", "Power Liftgate", "Dual Zone Climate", "Cargo Tray"]', '["9-inch Touchscreen", "Honda Navigation", "Apple CarPlay", "Bose Premium Sound"]', '["https://images.unsplash.com/photo-1626465041497-e2fd26ce18ba?w=800", "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800"]', NULL, false, true, true, 'Los Angeles, CA', 'Family', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (10, '2023-toyota-hilux-sr5', 'Toyota Hilux SR5 Plus', 'Toyota', 'Hilux', 'SR5 Plus', 2023, 58000.00, NULL, 5000, '2.8L Turbo Diesel', 'Automatic', 'Diesel', '4WD', 'Pickup', 5, 4, 'Silver Sky', 'AE-2023-012', NULL, 'new', 'available', 'The worlds most reliable pickup truck in premium SR5 Plus specification', 'The Toyota Hilux SR5 Plus is the benchmark by which all other pickup trucks are measured. Legendary reliability meets premium luxury.', '["SR5 Plus Package", "Sports Roll Bar", "Factory Tow Bar", "Leather Seats", "18-inch Alloys", "Bull Bar"]', '["Toyota Safety Sense", "Emergency Braking", "Lane Departure Warning", "Blind Spot Monitor"]', '["Leather Trim Seats", "Heated Front Seats", "Dual Zone Climate", "Power Driver Seat"]', '["8-inch Touchscreen", "Apple CarPlay", "Android Auto", "Satellite Navigation"]', '["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800", "https://images.unsplash.com/photo-1626465041497-e2fd26ce18ba?w=800"]', NULL, false, true, true, 'Los Angeles, CA', 'Pickup', '2026-04-12 11:09:50.906473', '2026-04-12 11:09:50.906473', false, NULL, NULL, 'in_stock', NULL, NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (11, '2019-toyota-prado-tx', '2019 Toyota Land Cruiser Prado TX', 'Toyota', 'Land Cruiser Prado', 'TX', 2019, 42000.00, NULL, 48000, '2.8L Diesel', 'Automatic', 'Diesel', '4WD', 'SUV', 7, 5, 'Pearl White', NULL, NULL, 'used', 'available', 'Grade 4.5 Toyota Prado TX from Japan. Low mileage, excellent condition.', 'This 2019 Toyota Land Cruiser Prado TX was sourced directly from a Japanese used car auction with grade 4.5. Features leather seats, navigation, reverse camera.', NULL, '["ABS", "Airbags (8)", "Lane Departure Warning", "Pre-Collision System"]', '["Leather Seats", "Navigation", "Reverse Camera", "Heated Seats", "Sunroof", "Bluetooth"]', NULL, '["https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=1200", "https://images.unsplash.com/photo-1583267746897-2cf415887172?w=1200"]', NULL, true, true, true, 'Nairobi, Kenya', NULL, '2026-04-12 12:25:47.381012', '2026-04-12 12:25:47.381012', true, '4.5', 'GRJ150-0123456', 'arrived', '2024-09-15', '2024-10-28', 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (12, '2020-nissan-x-trail-20xi', '2020 Nissan X-Trail 20Xi', 'Nissan', 'X-Trail', '20Xi', 2020, 28500.00, NULL, 31000, '2.0L Petrol', 'CVT', 'Petrol', '4WD', 'SUV', 7, 5, 'Graphite Blue', NULL, NULL, 'used', 'available', 'Grade 4 Nissan X-Trail 7-seater from Japan with ProPilot assist.', 'The 2020 Nissan X-Trail 20Xi features ProPilot semi-autonomous driving. Perfect 7-seater family SUV for Nairobi roads.', NULL, '["ProPilot Assist", "ABS", "Airbags (6)", "Emergency Brake", "Blind Spot Warning"]', '["ProPilot", "Navigation", "Around View Monitor", "Power Seats", "Dual Zone Climate", "Apple CarPlay"]', NULL, '["https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=1200", "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1200"]', NULL, false, true, true, 'Nairobi, Kenya', NULL, '2026-04-12 12:25:47.381012', '2026-04-12 12:25:47.381012', true, '4', 'NT32-987654', 'arrived', '2024-10-01', '2024-11-10', 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (13, '2021-mazda-cx5-25s-awd', '2021 Mazda CX-5 25S AWD', 'Mazda', 'CX-5', '25S AWD', 2021, 31000.00, NULL, 22000, '2.5L SKYACTIV-G', 'Automatic', 'Petrol', 'AWD', 'SUV', 5, 5, 'Soul Red Crystal', NULL, NULL, 'used', 'available', 'Grade 5 Mazda CX-5 in stunning Soul Red Crystal. Near-perfect condition.', 'Grade 5 Mazda CX-5 25S with Bose audio, heads-up display. The iconic Soul Red Crystal paint is a Mazda exclusive.', NULL, '["i-Activsense", "Lane Keep Assist", "Radar Cruise Control", "AEB"]', '["Bose 12-Speaker", "Heads-Up Display", "Wireless Charging", "Heated Seats", "Sunroof"]', NULL, '["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200", "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200"]', NULL, true, true, true, 'Nairobi, Kenya', NULL, '2026-04-12 12:25:47.381012', '2026-04-12 12:25:47.381012', true, '5', 'KF2P-456789', 'arrived', '2024-11-05', '2024-12-18', 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (14, '2018-honda-stepwgn-spada', '2018 Honda Stepwgn Spada', 'Honda', 'Stepwgn', 'Spada', 2018, 24000.00, NULL, 55000, '1.5L Turbo', 'CVT', 'Petrol', 'FWD', 'Van', 8, 5, 'Premium White Pearl', NULL, NULL, 'used', 'available', 'Honda Stepwgn Spada 8-seater minivan from Japan. Currently clearing at Mombasa Port.', 'Japan best-selling family minivan with magic sliding doors. Currently clearing customs at Mombasa — available in ~2 weeks.', NULL, '["Honda Sensing", "AEB", "Lane Watch Camera", "Airbags (6)"]', '["Magic Sliding Doors", "Panoramic Sunroof", "Navigation", "3-Row Seating"]', NULL, '["https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=1200"]', NULL, false, true, true, 'Mombasa Port (Clearing)', NULL, '2026-04-12 12:25:47.381012', '2026-04-12 12:25:47.381012', true, '4', 'RP3-0089123', 'clearing', '2025-01-10', NULL, 0, NULL, NULL);
INSERT INTO public.cars (id, slug, title, make, model, trim, year, price, discounted_price, mileage, engine_size, transmission, fuel_type, drivetrain, body_type, seats, doors, color, stock_number, vin, condition, availability, short_description, description, features, safety_features, comfort_features, tech_features, gallery, video_url, is_featured, is_published, financing_available, location, category, created_at, updated_at, is_japanese_import, auction_grade, chassis_number, shipping_status, japan_departure_date, kenya_arrival_date, view_count, price_floor, cost_price) VALUES (15, '2022-toyota-harrier-z', '2022 Toyota Harrier Z', 'Toyota', 'Harrier', 'Z Leather Package', 2022, 45000.00, NULL, 15000, '2.0L Dynamic Force', 'CVT', 'Petrol', 'FWD', 'SUV', 5, 5, 'Emotional Red', NULL, NULL, 'used', 'in_transit', 'Grade 5 Toyota Harrier Z in rare Emotional Red. Arriving April 2025.', 'The 4th generation Toyota Harrier Z in exclusive Emotional Red. Grade 5 with panoramic glass roof, JBL audio, digital rear mirror.', NULL, '["Toyota Safety Sense 2.0", "Pre-Collision System", "Radar Cruise", "Lane Tracing Assist"]', '["Panoramic Glass Roof", "Digital Rear Mirror", "JBL 9-Speaker", "Wireless CarPlay", "Heated Seats"]', NULL, '["https://images.unsplash.com/photo-1617469767786-9164a0f97d14?w=1200", "https://images.unsplash.com/photo-1580414057403-c5f451f30e1c?w=1200"]', NULL, true, true, true, 'In Transit — ETA April 2025', NULL, '2026-04-12 12:25:47.381012', '2026-04-12 12:25:47.381012', true, '5', 'MXUA80-0045123', 'in_transit', '2025-02-20', '2025-04-05', 0, NULL, NULL);


-- Data for Name: chatbot_knowledge; Type: TABLE DATA; Schema: public; Owner: -

INSERT INTO public.chatbot_knowledge VALUES (1, 'I want to talk to owner', 'Habari! Karibu. To speak with the **owner/management** at **AutoElite Motors**, please use either of these:

- **Call / WhatsApp:** **+254 700 234 567**
- **Email:** **sales@autoelitemotors.co.ke**

If you prefer, you can also visit us at **Ngong Road, Nairobi (next to Prestige Plaza)** during **Mon–Sat 8AM–6PM | Sun 10AM–4PM**.

Share your **name** and what it’s about (buying, selling, complaint, partnership), and I’ll guide you on the fastest way to get you connected.', '["talk","owner"]', 'openai', 0, '2026-04-18 14:23:42.638594', '2026-04-18 14:23:42.638594');
INSERT INTO public.chatbot_knowledge VALUES (2, 'My name is John', 'Habari John, karibu sana.

To get you connected to the **owner/management**, please send this message on **WhatsApp: +254 700 234 567** (or call the same number):

**Template to copy-paste:**
- *Hi AutoElite, my name is John. I’d like to speak with the owner/management regarding [brief reason]. What’s the best time to reach them? My number is [your phone].*

Tell me what it’s about (e.g., **car inquiry, financing, complaint, partnership**) and I’ll help you phrase it vizuri.', '["name","john"]', 'openai', 0, '2026-04-18 14:24:05.49265', '2026-04-18 14:24:05.49265');


-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: -

INSERT INTO public.services VALUES (1, 'Premium Car Sales', 'We offer an exclusive selection of verified premium vehicles from the world''s leading manufacturers. Every car in our inventory undergoes a rigorous inspection process.', 'Car', true, 1, '2026-04-12 11:09:50.926308');
INSERT INTO public.services VALUES (2, 'Vehicle Sourcing', 'Can''t find your dream car in our current inventory? Our global network allows us to source specific makes, models, and configurations to your exact requirements.', 'Search', true, 2, '2026-04-12 11:09:50.926308');
INSERT INTO public.services VALUES (3, 'Financing Support', 'We offer flexible financing options through our network of trusted financial partners. Competitive rates, straightforward terms, and quick approvals.', 'CreditCard', true, 3, '2026-04-12 11:09:50.926308');
INSERT INTO public.services VALUES (4, 'Trade-In Service', 'Get a fair, transparent valuation for your current vehicle and apply it directly to your next purchase. We accept all makes and models.', 'ArrowLeftRight', true, 4, '2026-04-12 11:09:50.926308');
INSERT INTO public.services VALUES (5, 'Vehicle Inspection', 'Every vehicle is subjected to a comprehensive 200-point inspection before entering our inventory. We provide full inspection reports on request.', 'ClipboardCheck', true, 5, '2026-04-12 11:09:50.926308');
INSERT INTO public.services VALUES (6, 'Documentation Support', 'Our experienced team handles all paperwork including title transfers, registration, and any import documentation required.', 'FileText', true, 6, '2026-04-12 11:09:50.926308');
INSERT INTO public.services VALUES (7, 'After-Sale Guidance', 'Our relationship with clients does not end at the sale. We provide ongoing support, service recommendations, and guidance for all post-purchase needs.', 'HeartHandshake', true, 7, '2026-04-12 11:09:50.926308');
INSERT INTO public.services VALUES (8, 'Import Assistance', 'We specialize in sourcing and importing premium vehicles from international markets. Full customs clearance and compliance management included.', 'Globe', true, 8, '2026-04-12 11:09:50.926308');


-- Data for Name: site_settings; Type: TABLE DATA; Schema: public; Owner: -

INSERT INTO public.site_settings VALUES (1, 'Elite Motors', 'Kenya''s Premier Luxury Car Dealership', '+254 734336227', '254734336227', 'sales@autoelitemotors.co.ke', 'Ngong Road, next to Prestige Plaza', 'Nairobi', 'https://maps.google.com/?q=4820+Automotive+Boulevard+Los+Angeles+CA', 'https://facebook.com/autoelitemotors', 'https://instagram.com/autoelitemotors', 'https://twitter.com/autoelitemotors', 'https://youtube.com/@autoelitemotors', 'Mon-Sat: 8:00AM - 7:00PM  |  Sunday: 10:00AM - 5:00PM', 'Drive the Extraordinary', 'Premium vehicles sourced from Japan and beyond — delivered in Nairobi', 'About AutoElite Motors', 'For over 15 years, AutoElite Motors has been Los Angeles''s most trusted premium car dealership. We specialize in luxury, performance, and premium vehicles, offering an unparalleled buying experience with full transparency, competitive pricing, and exceptional after-sale support. Our passionate team of automotive experts is dedicated to matching every customer with their perfect vehicle.', 'https://images.unsplash.com/photo-1562141961-9e5cf8f9c0f0?w=800', 12, 80, 2400, '2026-04-12 14:41:04.501', 'Kenya', '', '', 'KES', 130, NULL, NULL, NULL, NULL, NULL, NULL, 'Nairobi''s home for premium Japanese imports & luxury cars', 'true', NULL, 'AutoElite Motors — Premium car dealership in Nairobi, Kenya. Japanese imports, luxury vehicles, KRA import assistance.', '', NULL, '#DC2626', '{"SUV":"","Luxury":"","Sports":"","Sedan":""}', 'true');


-- Data for Name: team_members; Type: TABLE DATA; Schema: public; Owner: -

INSERT INTO public.team_members VALUES (1, 'Michael Sterling', 'Founder & Principal Dealer', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'Luxury & Exotic Vehicles', '+1 (555) 234-5678', '+15552345678', 'michael@autoelitemotors.com', 'With over 20 years in the premium automotive industry, Michael founded AutoElite Motors with a vision to redefine the car buying experience in Los Angeles. His passion for extraordinary vehicles and commitment to customer satisfaction are the cornerstones of our success.', 1, '2026-04-12 11:09:50.921157');
INSERT INTO public.team_members VALUES (2, 'Alexandra Brooks', 'Senior Sales Consultant', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'European Luxury Brands', '+1 (555) 234-5679', '+15552345679', 'alexandra@autoelitemotors.com', 'Alexandra brings 12 years of luxury automotive experience, specializing in European marques including Mercedes-Benz, BMW, Audi, and Porsche. Her encyclopedic knowledge of these vehicles ensures every client finds their perfect match.', 2, '2026-04-12 11:09:50.921157');
INSERT INTO public.team_members VALUES (3, 'James Park', 'Finance Manager', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Vehicle Financing & Leasing', '+1 (555) 234-5680', '+15552345680', 'james@autoelitemotors.com', 'James has helped thousands of clients secure the best possible financing terms for their dream vehicles. With relationships across major financial institutions, he consistently delivers competitive rates and flexible terms.', 3, '2026-04-12 11:09:50.921157');
INSERT INTO public.team_members VALUES (4, 'Sofia Martinez', 'Client Relations Manager', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'After-Sale Support & Trade-Ins', '+1 (555) 234-5681', '+15552345681', 'sofia@autoelitemotors.com', 'Sofia ensures that every client who leaves our showroom becomes a lifelong partner. From trade-in valuations to post-purchase support, she is dedicated to creating an exceptional experience that extends well beyond the sale.', 4, '2026-04-12 11:09:50.921157');


-- Data for Name: testimonials; Type: TABLE DATA; Schema: public; Owner: -

INSERT INTO public.testimonials VALUES (1, 'James Richardson', 'Beverly Hills, CA', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200', 5, 'Absolutely incredible experience. The team at AutoElite went above and beyond to find me the perfect Mercedes GLE. Professional, transparent, and genuinely passionate about cars. I will never buy from anywhere else.', 'Mercedes-Benz GLE 350', true, '2026-04-12 11:09:50.914688');
INSERT INTO public.testimonials VALUES (2, 'Sarah Mitchell', 'Malibu, CA', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200', 5, 'From the moment I walked in, I felt like a valued customer. No pressure tactics, just genuine expertise and honest advice. My Range Rover Sport is everything I dreamed of. The financing process was smooth and fair.', 'Range Rover Sport HSE', true, '2026-04-12 11:09:50.914688');
INSERT INTO public.testimonials VALUES (3, 'Marcus Johnson', 'Santa Monica, CA', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200', 5, 'I was skeptical about buying a used car, but AutoElite completely changed my perspective. Full vehicle history, independent inspection, and a 3-month warranty included. My BMW X5 is in flawless condition.', 'BMW X5 M50i', true, '2026-04-12 11:09:50.914688');
INSERT INTO public.testimonials VALUES (4, 'Elena Rodriguez', 'Los Angeles, CA', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200', 5, 'The trade-in process was incredibly fair and transparent. They gave me top dollar for my old car and made the upgrade to the Porsche Cayenne seamlessly easy. Exceptional service from start to finish.', 'Porsche Cayenne S', true, '2026-04-12 11:09:50.914688');
INSERT INTO public.testimonials VALUES (5, 'David Thompson', 'Pasadena, CA', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200', 5, 'AutoElite sourced my dream Audi RS6 Avant within 2 weeks from their network. Exactly the spec I wanted, at a fair price, with full documentation. This is how car buying should always work.', 'Audi RS6 Avant', true, '2026-04-12 11:09:50.914688');
INSERT INTO public.testimonials VALUES (6, 'Amanda Chen', 'Studio City, CA', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200', 5, 'My husband and I both bought our cars from AutoElite within the same month. The family discount was a wonderful touch, but honestly the transparency and professionalism is why we keep coming back.', 'Toyota Alphard Executive Lounge', true, '2026-04-12 11:09:50.914688');


-- Name: blog_posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -

SELECT pg_catalog.setval('public.blog_posts_id_seq', 3, true);


-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -

SELECT pg_catalog.setval('public.cars_id_seq', 15, true);


-- Name: chatbot_knowledge_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -

SELECT pg_catalog.setval('public.chatbot_knowledge_id_seq', 2, true);


-- Name: services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -

SELECT pg_catalog.setval('public.services_id_seq', 8, true);


-- Name: site_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -

SELECT pg_catalog.setval('public.site_settings_id_seq', 1, true);


-- Name: team_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -

SELECT pg_catalog.setval('public.team_members_id_seq', 4, true);


-- Name: testimonials_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -

SELECT pg_catalog.setval('public.testimonials_id_seq', 6, true);



-- ============================================================================
-- Default admin user
-- ============================================================================
-- Username: admin
-- Password: admin123  ← CHANGE THIS IMMEDIATELY after first login (Settings → Account)
-- Role:     owner (full access)
-- ============================================================================

INSERT INTO admin_users (id, username, password_hash, name, created_at, last_login_at, role, is_active, email)
VALUES (1, 'admin', 'c65852e7b6466c4e7d83e74ab427cf2b549ab1cd05a46fe860c375c9139c6852', 'Administrator', NOW(), NULL, 'owner', 'true', NULL)
ON CONFLICT (username) DO NOTHING;

SELECT pg_catalog.setval('public.admin_users_id_seq', 1, true);

COMMIT;

-- ============================================================================
-- Done! Visit your site and log in at /admin/login
-- ============================================================================
